name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # Run tests.
  test:
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Keychain
        uses: sinoru/actions-setup-keychain@v1.0

      - name: Test
        run: go test ./...

      - name: Remove old XCode SDKs
        run: sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: build --clean --snapshot

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: pinentry-touchid
          path: dist/*
